package bot

import (
	"fmt"
	"image"
	"image/color"
	"image/draw"
	"image/png"
	"math"
	"os"
	"strings"
	"time"

	"github.com/avvvet/siloam/db"
	"golang.org/x/image/font"
	"golang.org/x/image/font/basicfont"
	"golang.org/x/image/math/fixed"
)

// calculateBill computes each unit's bill share from readings and previous readings
func calculateBill(readings map[string]*db.Reading, previous map[string]int, totalBill float64) *db.Bill {
	bill := &db.Bill{
		TotalBill: totalBill,
		Units:     make(map[string]float64),
		Diffs:     make(map[string]int),
		Percents:  make(map[string]float64),
		Previous:  make(map[string]int),
		Current:   make(map[string]int),
	}

	totalUsage := 0
	for _, unit := range allUnits {
		r, ok := readings[unit]
		if !ok {
			continue
		}
		prev := previous[unit]
		diff := r.Value - prev
		if diff < 0 {
			diff = 0
		}
		bill.Previous[unit] = prev
		bill.Current[unit] = r.Value
		bill.Diffs[unit] = diff
		totalUsage += diff
	}

	for _, unit := range allUnits {
		if totalUsage == 0 {
			bill.Units[unit] = 0
			bill.Percents[unit] = 0
			continue
		}
		diff := bill.Diffs[unit]
		pct := float64(diff) / float64(totalUsage) * 100
		amount := pct / 100 * totalBill
		bill.Percents[unit] = math.Round(pct*100) / 100
		bill.Units[unit] = math.Round(amount*100) / 100
	}

	return bill
}

// generateBillImage creates a PNG bill image and returns the file path
func generateBillImage(bill *db.Bill, creatorUsername string) (string, error) {
	loc, _ := time.LoadLocation("Europe/Moscow")
	now := time.Now().In(loc)
	monthStr := now.Format("January 2006")
	dateStr := now.Format("January 02, 2006")

	// Image dimensions
	width := 900
	rowHeight := 28
	headerRows := 6
	tableRows := len(allUnits) + 2 // units + header + total
	footerRows := 3
	height := (headerRows+tableRows+footerRows)*rowHeight + 60

	img := image.NewRGBA(image.Rect(0, 0, width, height))

	// Background
	draw.Draw(img, img.Bounds(), &image.Uniform{color.White}, image.Point{}, draw.Src)

	// Colors
	headerBg := color.RGBA{30, 80, 160, 255} // dark blue
	tableHeaderBg := color.RGBA{70, 130, 200, 255}
	rowEven := color.RGBA{240, 246, 255, 255}
	rowOdd := color.RGBA{255, 255, 255, 255}
	textDark := color.RGBA{30, 30, 30, 255}
	textWhite := color.RGBA{255, 255, 255, 255}
	footerBg := color.RGBA{245, 245, 245, 255}
	borderColor := color.RGBA{200, 210, 230, 255}

	face := basicfont.Face7x13

	drawText := func(x, y int, c color.Color, text string) {
		d := &font.Drawer{
			Dst:  img,
			Src:  image.NewUniform(c),
			Face: face,
			Dot:  fixed.P(x, y),
		}
		d.DrawString(text)
	}

	fillRect := func(x, y, w, h int, c color.Color) {
		for row := y; row < y+h; row++ {
			for col := x; col < x+w; col++ {
				img.Set(col, row, c)
			}
		}
	}

	drawHLine := func(x, y, w int, c color.Color) {
		for col := x; col < x+w; col++ {
			img.Set(col, y, c)
		}
	}

	y := 10

	// Title header background
	fillRect(0, y, width, rowHeight*3, headerBg)
	drawText(width/2-120, y+15, textWhite, fmt.Sprintf("WATER BILL REPORT — %s", strings.ToUpper(monthStr)))
	drawText(width/2-80, y+35, textWhite, fmt.Sprintf("Date: %s", dateStr))
	drawText(width/2-100, y+55, textWhite, fmt.Sprintf("Total Bill: %.0f Birr", bill.TotalBill))
	y += rowHeight*3 + 10

	// Table columns: Unit | Previous | Current | Diff | % | Amount
	cols := []string{"Unit", "Previous", "Current", "Diff", "%", "Amount (Birr)"}
	colWidths := []int{80, 120, 120, 100, 100, 160}
	colX := []int{20, 100, 220, 340, 440, 540}

	// Table header row
	fillRect(0, y, width, rowHeight, tableHeaderBg)
	for i, col := range cols {
		drawText(colX[i]+5, y+18, textWhite, col)
		_ = colWidths[i]
	}
	y += rowHeight

	// Unit rows
	var totalAmount float64
	for idx, unit := range allUnits {
		bg := rowOdd
		if idx%2 == 0 {
			bg = rowEven
		}
		fillRect(0, y, width, rowHeight, bg)
		drawHLine(0, y, width, borderColor)

		prev := bill.Previous[unit]
		curr := bill.Current[unit]
		diff := bill.Diffs[unit]
		pct := bill.Percents[unit]
		amount := bill.Units[unit]
		totalAmount += amount

		drawText(colX[0]+5, y+18, textDark, strings.ToUpper(unit))
		drawText(colX[1]+5, y+18, textDark, fmt.Sprintf("%d", prev))
		drawText(colX[2]+5, y+18, textDark, fmt.Sprintf("%d", curr))
		drawText(colX[3]+5, y+18, textDark, fmt.Sprintf("%d", diff))
		drawText(colX[4]+5, y+18, textDark, fmt.Sprintf("%.2f%%", pct))
		drawText(colX[5]+5, y+18, textDark, fmt.Sprintf("%.0f Birr", amount))
		y += rowHeight
	}

	// Total row
	fillRect(0, y, width, rowHeight, tableHeaderBg)
	drawText(colX[0]+5, y+18, textWhite, "TOTAL")
	drawText(colX[5]+5, y+18, textWhite, fmt.Sprintf("%.0f Birr", totalAmount))
	y += rowHeight + 10

	// Footer
	fillRect(0, y, width, rowHeight*3, footerBg)
	drawHLine(0, y, width, borderColor)
	drawText(20, y+15, textDark, "Report is generated by automated system and hosted on generously provided U.S server.")
	drawText(20, y+33, textDark, fmt.Sprintf("Manager: Siloam  |  Creator: %s", creatorUsername))
	drawText(20, y+51, textDark, fmt.Sprintf("Generated: %s", now.Format("02 Jan 2006 15:04 MST")))

	// Save to temp file
	path := fmt.Sprintf("/tmp/bill_%s.png", now.Format("2006-01"))
	f, err := os.Create(path)
	if err != nil {
		return "", err
	}
	defer f.Close()

	if err := png.Encode(f, img); err != nil {
		return "", err
	}

	return path, nil
}
